---
- hosts: webservers:loadbalancers 
  become: true

  tasks:
  - name: installing apache
    yum: 
      name: httpd 
      state: latest

  - name: enable httpd
    service:
      name: httpd
      state: started

  - name: creating file 
    file: 
      path: /var/www/html/index.html
      state: touch 

  - name: adding line to index file
    lineinfile:
      path: /var/www/html/index.html
      line: "hello World Sivaram Dachineni"

  # - name: installing database
  #   yum: name=postgresql state=latest
  
  # - name: starting postgresql service 
  #   service: name=postgresql state=started 



