---
- hosts: webservers
  become: yes
  tasks:
    - name: download transaction_list
      block:
        - get_url:
            url: http://apps.l33t.com/transaction_list
            dest: /home/ansible/transaction_list
        - replace:
            path: /home/ansible/transaction_list
            regexp: "#BLANKLINE"
            replace: '\n'
        - debug: msg="File Downloaded"
      rescue:
        - debug: msg="133t.com appers to be down. try again later. "
      always:
        - debug: msg="Attempted completed."


